fft.awin = 'ham'
fft.awidth = 1
fft.aalpha = 0.6
fft.ashift = 0
fft.zerofill = 1
fft.rshift = 0
fft.lshift = 0
fft.opt = 'ftir'
fft.midpoint = 4500
fft.xscale = 1
fft.cta = 100
fft.phase0 = 0
fft.bsline='polyfit1D'
fft.n_pol = 1
