
hh = fittingbox;

aa = get(hh, 'Children');

uiCTRL = {};
uiMENU = {};
uiMENU_po = [];
for ii = 1:length(aa);
    str = get(aa(ii));
    if strcmp(str.Type, 'uicontrol')
        if iscell(str.String)
            sss = '{';
            for kk = 1:length(str.String)
                sss = [sss, ', ''', str.String{kk}, ''''];
            end
            sss = [sss, '}'];
        else
            sss = str.String;
        end
        uiCTRL{end+1} = ['handles.', str.Tag, ' = uicontrol(handles.figure1, ' ...
                '''Style'', ''' , str.Style, ''', ', ...
                '''Tag'', ''' , str.Tag, ''', ', ...
                '''String'', ''', sss, ''', ',...
                '''Value'', ' , num2str(str.Value), ', ' ,...
                '''Units'', ''pixels'', ', ...
                '''Callback'', ''' , str.Callback ,''''...
                ');'];
    end
    if strcmp(str.Type, 'uimenu')
       
        uiMENU{end+1} = ['handles.', str.Tag, ' = uimenu(handles.', get(str.Parent, 'Tag'), ', ' ...
                '''Tag'', ''' , str.Tag, ''', ' ,...
                '''Label'', ''', str.Label, ''', ',...
                '''Checked'', ''' , str.Checked, ''', ', ...
                '''Separator'', ''', str.Separator, ''', ',...
                '''Callback'', ''' , str.Callback, ''' ' ...
                ');'];
            uiMENU_po(end+1) = str.Position(1);
            if ~isempty(str.Children)
                for mm = length(str.Children):-1:1
                     str1 = get(str.Children(mm));
                        uiMENU{end+1} = ['handles.', str1.Tag, ' = uimenu(handles.', get(str1.Parent, 'Tag'), ', ', ...
                        '''Tag'', ''' , str1.Tag, ''', ' ,...
                        '''Label'', ''', str1.Label, ''', ',...
                        '''Checked'', ''' , str1.Checked, ''', ', ...
                        '''Separator'', ''', str1.Separator, ''', ',...
                        '''Callback'', ''' , str1.Callback, ''', ' ...
                        '''Accelerator'', ''' , str1.Accelerator, ''' ' ...
                        ');'];
                        uiMENU_po(end+1) = str.Position(1);
                end
            end
    end
    if strcmp(str.Type, 'uicontextmenu')
       
        uiMENU{end+1} = ['handles.', str.Tag, ' = uicontextmenu(handles.', get(str.Parent, 'Tag'), ', ', ...
                '''Tag'', ''' , str.Tag, ''', ', ...
                '''Callback'', ''' , str.Callback, ''' ' ...
                ');'];
            uiMENU_po(end+1) = str.Position(1);
            if ~isempty(str.Children)
                for mm = 1:length(str.Children)
                     str1 = get(str.Children(mm));
                        uiMENU{end+1} = ['handles.', str1.Tag, ' = uimenu(handles.', get(str1.Parent, 'Tag'), ', ', ...
                        '''Tag'', ''' , str1.Tag, ''', ', ...
                        '''Label'', ''', str1.Label, ''', ',...
                        '''Checked'', ''' , str1.Checked, ''', ' ,...
                        '''Separator'', ''', str1.Separator, ''', ',...
                        '''Callback'', ''' , str1.Callback, ''' ' ...
                        ');'];
                    uiMENU_po(end+1) = str.Position(1);
                end
            end
    end
    
end
fid = fopen('getcomponents_out.m', 'w');
try
    for jj = 1:length(uiMENU)
        fprintf(fid, '%s \n\r', uiMENU{jj});
    end
    for jj = 1:length(uiCTRL)
        fprintf(fid, '%s \n\r', uiCTRL{jj});
    end
end
fclose(fid)


open getcomponents_out.m;


